### ISSUE TITLE
match function against an array element

### ISSUE THREAD

**Issue by NuSkooler** [hiltontj/serde_json_path#103]
Hi! I'm attempting to use a JSONPath expression with `match` of an array element, but am struggling a bit.

Here is what I have and want to do:

```json
{
  "foo": [
    {
      "name": "bar",
      "value": "baz"
    },
    {
      "name": "foobar",
      "value": "barfoo"
    }
  ]
}
```

I would like to `match` against value's in the array:

`$[?match([$.foo[?(@.name=='foobar')].value, 'whatever')]`

Everything I have tried results in a parse error. Any ideas? I've tried various methods to attempt to return a single value, ie: `[0]`, but perhaps it's not supported, or I'm just doing it wrong!

**Comment by hiltontj** [comment]
Hey @NuSkooler - what is the desired output of your query that you are going for?

FWIW, the [sandbox](https://serdejsonpath.live/) does need to be updated, but you can try queries there.

**Comment by hiltontj** [comment]
You could combine multiple `match`es with a logical `&&`, like so:
```
$.foo[? match(@.name, 'foobar') && match(@.value, '[A-Za-z]*foo')].value
```
I tried that out in the sandbox and it yields `["barfoo"]` in the query result for the sample JSON in the original issue.

**Comment by NuSkooler** [comment]
Thanks, this is great! One last question: I'm trying a logical 'not' in my regex, ie: "everything but this". I this supported by the engine?

**Comment by NuSkooler** [comment]
Thank you so much for you help, I think it has all "clicked"!

**Comment by hiltontj** [comment]
I am not sure about using a 'not' _inside_ the regex, but JSONPath supports standard logical operators, and since the `match` function returns a `LogicalType` (see [JSONPath Type System](https://www.rfc-editor.org/rfc/rfc9535.html#name-type-system-for-function-ex)), then you can 'not' it with a `!`, e.g.,
```
$.foo[? !match(@.name, 'foobar')].value
```

**Comment by hiltontj** [comment]
> Thank you so much for you help, I think it has all "clicked"!

You're welcome! Thanks for using `serde_json_path` 🙏
