### ISSUE TITLE
release 0.6.1

### ISSUE THREAD

**Issue by yanns** [hiltontj/serde_json_path#47]
There's a 0.6.1 release on https://crates.io/crates/serde_json_path
But the tag does not seem to exist in the git repository.
Maybe a forgotten push?

**Comment by hiltontj** [comment]
Hey @yanns - I did forget to tag the release! Thank you for bringing this to my attention. I have just done so by creating the `v0.6.1` release tag. I also opened a PR that adds that step to my release checklist, so I won't make that mistake again.

**Comment by yanns** [comment]
awesome!
